project_id = "orcbxgajfhgmjobsjlix"

[functions.evolution-webhook]
verify_jwt = false

[functions.process-broadcast-queue]
verify_jwt = false

[functions.create-google-calendar-event]
verify_jwt = false

[functions.log-auth-attempt]
verify_jwt = false

[functions.bubble-send-whatsapp]
verify_jwt = false

[functions.bubble-list-instances]
verify_jwt = false

[functions.bubble-check-status]
verify_jwt = false
