project_id = "orcbxgajfhgmjobsjlix"

[functions.evolution-webhook]
verify_jwt = false

[functions.process-broadcast-queue]
verify_jwt = false

[functions.create-google-calendar-event]
verify_jwt = false
